version: 1

services:
  - type: pserv
    name: hs-validator-db
    plan: free

  - type: web
    name: hs-code-validator
    env: docker
    rootDirectory: ./backend
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: hs-validator-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: hs-validator-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: hs-validator-db
          property: password
    healthCheckPath: /actuator/health