version: 1

databases:
  - name: hs_validator
    databaseName: hs_code_validator
    user: hs_code
    plan: free

services:
  - type: web
    name: hs-code-validator
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile

    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production

      - key: GEMINI_API_KEY
        sync: false

      - key: LOGISTICS_CUSTOMS_API_URL
        value: https://comtrade.un.org/data/doc/api/

      - key: PGHOST
        fromDatabase:
          name: hs_validator
          property: host

      - key: PGPORT
        fromDatabase:
          name: hs_validator
          property: port

      - key: PGDATABASE
        fromDatabase:
          name: hs_validator
          property: database

      - key: PGUSER
        fromDatabase:
          name: hs_validator
          property: user

      - key: PGPASSWORD
        fromDatabase:
          name: hs_validator
          property: password

    healthCheckPath: /actuator/health
