version: 1

services:
  - type: pserv
    name: hs_validator
    plan: free

  - type: web
    name: HS-Code-Validator
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: hs-validator-db
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: hs-validator-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: hs-validator-db
          property: password
    healthCheckPath: /actuator/health