version: 1
services:
  - type: pserv
    name: hs-validator-db
    plan: free
    databaseName: hs_validator
    runtime: docker
    user: postgres

  - type: web
    name: HS-Code-Validator
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
    healthCheckPath: /actuator/health
    healthCheckTimeout: 180