version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: hs_validator_db
    environment:
      POSTGRES_DB: hs_validator
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hs-network

  app:
    build: .
    container_name: hs_validator_app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hs_validator
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - postgres
    networks:
      - hs-network

networks:
  hs-network:
    driver: bridge

volumes:
  postgres_data: